"""Write the human-readable rubric docs from config/report_types.yaml.

    python export_rubrics.py            # rewrite both *-intelligence-rubric.md
    python export_rubrics.py --check    # exit 1 if either file is stale

The config is the rubric: those `criteria` blocks are verbatim what the model
receives. The two markdown files at the repo root are for people - they are what
gets read in a review meeting - and nothing reads them at runtime. That split is
useful right up until they disagree, at which point a reviewer edits a file with
no effect on judging. So they are generated, not maintained: change the YAML, run
this, commit both.

`--check` is the guard worth wiring into a pre-commit hook or CI.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
CONFIG = ROOT / "config" / "report_types.yaml"

BANNER = (
    "<!-- GENERATED by export_rubrics.py from config/report_types.yaml. Do not edit "
    "this file: edit the YAML and re-run, or your change will not reach the model. -->"
)

# The plain-text criteria use SHOUTED section labels. Promote them to markdown
# headings so the doc has structure, without rewording anything.
SECTION = re.compile(r"^([A-Z][A-Z0-9 ,/&'\-]{3,})(:|\s*-|\.)?\s*$")
INLINE_SECTION = re.compile(r"^([A-Z][A-Z0-9 ,/&'\-]{3,}):\s+(.*)$")


def to_markdown(text: str) -> str:
    """Light structural pass over an authored criteria block.

    Deliberately conservative: it promotes headings and leaves every word alone.
    A generator that rewrote the prose would make the doc a paraphrase, and the
    whole point is that the doc says what the model is told.
    """
    out: list[str] = []
    for raw in text.rstrip().splitlines():
        line = raw.rstrip()
        if not line.strip():
            out.append("")
            continue
        stripped = line.strip()
        match = SECTION.match(stripped)
        if match and not stripped.startswith("-"):
            out.append(f"### {match.group(1).strip().title()}")
            continue
        inline = INLINE_SECTION.match(stripped) if not stripped.startswith("-") else None
        if inline:
            out.append(f"### {inline.group(1).strip().title()}")
            out.append("")
            out.append(inline.group(2).strip())
            continue
        out.append(line)
    # Collapse the runs of blank lines the heading promotion can leave behind.
    text = "\n".join(out)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def build_doc(key: str, spec: dict, config: dict) -> str:
    """One report type's rubric doc, in the order the model receives it."""
    labels = ", ".join(cat["label"] for cat in spec["categories"].values())
    parts = [
        BANNER,
        "",
        f"# What Counts as Meaningful: {spec['brandmark']}",
        "",
        f"**Categories:** {labels}",
        "",
        f"**Watchlist:** `{spec['watchlist']}` &nbsp;·&nbsp; "
        f"**Rank used:** {'yes' if spec.get('use_rank') else 'no'}",
        "",
        "## Evidence standard",
        "",
        "_Shared by both report types and applied first: an article that fails any of these is "
        "excluded however interesting its subject._",
        "",
        to_markdown(config.get("evidence_standard", "")),
        "",
        "## Criteria",
        "",
        to_markdown(spec["criteria"]),
    ]

    for field, title in (("rank_note", "Ranking and escalation"),
                         ("tier_note", "Competitor tiers and escalation")):
        if spec.get(field):
            parts += ["", f"## {title}", "", to_markdown(spec[field])]

    tiers = config.get("source_tiers") or {}
    order = tiers.get("order") or []
    if order:
        line = tiers.get("citable_max_position")
        parts += ["", "## Sources", ""]
        if line:
            parts.append(
                f"Tiers 1&ndash;{line} may be **cited**. Anything below is used for "
                "**discovery only** and can never be the link the briefing shows; an event whose "
                "only coverage sits below the line is dropped and named in the run log."
            )
            parts.append("")
        parts.append("| # | Tier | Cited? | Domains |")
        parts.append("|---|------|--------|---------|")
        for i, tier in enumerate(order, start=1):
            cited = "yes" if line and i <= line else ("no" if line else "n/a")
            domains = ", ".join(f"`{d}`" for d in (tier.get("domains") or [])) or "_unlisted_"
            parts.append(f"| {i} | {tier.get('label', '')} | {cited} | {domains} |")

    parts += [
        "",
        "## Priority",
        "",
        "| Key | Shown as |",
        "|-----|----------|",
    ]
    for pkey, pri in config["priorities"].items():
        parts.append(f"| `{pkey}` | {pri['label']} |")

    return "\n".join(parts).rstrip() + "\n"


def target_for(key: str) -> Path:
    return ROOT / f"{key[:-1] if key.endswith('s') else key}-intelligence-rubric.md"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify the docs match the config; write nothing")
    args = ap.parse_args()

    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    stale = []
    for key, spec in config["report_types"].items():
        path = target_for(key)
        doc = build_doc(key, spec, config)
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if args.check:
            if current != doc:
                stale.append(path.name)
            continue
        path.write_text(doc, encoding="utf-8")
        verb = "unchanged" if current == doc else ("written" if current else "created")
        print(f"{path.name}: {verb} ({len(doc):,} bytes)")

    if args.check:
        if stale:
            print(f"stale, re-run export_rubrics.py: {', '.join(stale)}", file=sys.stderr)
            return 1
        print("rubric docs match the config")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
