"""Judge the article FIXTURES and write the alerts files - no search, no date range.

This is the offline path: it judges whatever is in data/mock_articles_*.json and
regenerates data/sample_alerts_*.json, which build_preview.py renders into docs/.
Useful for iterating on criteria without spending Tavily credits.

For a live run over the real watchlists with a clickable date range, use
`python serve.py`.

    python generate_summaries.py                      # both report types
    python generate_summaries.py --type competitors    # just one
    python generate_summaries.py --verbose             # print route + server model id
    python generate_summaries.py --model api-gpt-oss-120b
    python generate_summaries.py --limit 2            # first two entities per type

Requires TRITONAI_API_KEY in .env; without it the call raises rather than falling back.
"""

from __future__ import annotations

import argparse
import json
import sys

# .env must be loaded BEFORE utils.connect is imported - connect.py reads
# os.environ at call time, and this is a script, not a notebook.
from dotenv import load_dotenv

load_dotenv()

from judge import judge_entities  # noqa: E402
from render import ROOT, load_config, load_json, read_watchlist  # noqa: E402
from sources import citable_limit, source_tiers  # noqa: E402
from utils.connect import DEFAULT_MODEL, get_client  # noqa: E402


def run_type(key: str, spec: dict, args) -> tuple[int, int, list[str]]:
    """Judge every entity in one report type's article fixture."""
    print(f"\n=== {spec['label']} ===")
    config = load_config()
    fixture = load_json(ROOT / spec["articles"])
    watchlist = read_watchlist(ROOT / spec["watchlist"])

    entities = fixture.get("companies", [])
    if args.limit:
        entities = entities[: args.limit]

    kept_entities, kept, dropped, failed = judge_entities(
        entities,
        spec,
        model=args.model,
        client=get_client(),  # one client reused across every entity
        verbose=args.verbose,
        progress=lambda m: print(f"  {m}", flush=True),
        standard=config.get("evidence_standard", ""),
        tiers=source_tiers(config),
        citable_max=citable_limit(config),
        # No date window offline: the fixtures are a fixed set that would age out
        # and leave this script printing an empty digest a week after it was
        # written. Live runs get the window from the range the user picked.
        window_start=None,
    )

    payload = {
        "_note": (
            f"Generated by generate_summaries.py via TritonAI ({args.model}) for report type "
            f"'{key}'. Source articles are fictional."
        ),
        "run_date": fixture.get("run_date", ""),
        "period_label": fixture.get("period_label", ""),
        "portfolio_size": len(watchlist) or fixture.get("portfolio_size", 0),
        "companies": kept_entities,
    }
    out_path = ROOT / spec["alerts"]
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"  -> {kept} kept, {dropped} excluded, written to {spec['alerts']}")
    return kept, dropped, failed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--type", default="all", help="report type: tenants, competitors, or all")
    ap.add_argument("--model", default=DEFAULT_MODEL, help=f"TritonAI model id (default: {DEFAULT_MODEL})")
    ap.add_argument("--limit", type=int, default=0, help="judge only the first N entities per type")
    ap.add_argument("--verbose", action="store_true", help="print route and server-reported model")
    args = ap.parse_args()

    specs = load_config()["report_types"]
    if args.type == "all":
        wanted = list(specs)
    elif args.type in specs:
        wanted = [args.type]
    else:
        sys.exit(f"error: unknown report type {args.type!r} - choose from {', '.join(specs)}, or all")

    total_kept = total_dropped = 0
    all_failed: list[str] = []
    for key in wanted:
        kept, dropped, failed = run_type(key, specs[key], args)
        total_kept += kept
        total_dropped += dropped
        all_failed += failed

    print(f"\n{total_kept} findings kept, {total_dropped} excluded across {len(wanted)} report type(s)")
    if all_failed:
        # Surfaced loudly rather than silently shrinking a digest.
        print(f"{len(all_failed)} entity/entities skipped on error: {', '.join(all_failed)}", file=sys.stderr)
    print("next: python build_preview.py --open")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
