"""Ingest stage - AAT Excel workbooks -> local watchlists.

NOTE: the hand-maintained rosters at the repo root (tenant-list.md,
competitor-list.md) are the point of reference for live runs - they carry the
priority rank and category columns this script cannot recover from a raw sheet.
This script stays for bulk re-extraction from a fresh workbook.

Reads the tenant roster and the competitor list and writes the two watchlist files
that drive live runs. ONLY names and cities are extracted; rent, GLA, lease dates,
suite and building ids are read past and never written anywhere.

    python ingest.py --list                       # show sheets/columns, write nothing
    python ingest.py                              # both lists, default paths
    python ingest.py --segment office              # office tenants only
    python ingest.py --city "San Diego"            # one market
    python ingest.py --limit 40                    # cap per list

Names arrive SHOUTED and suffixed ("LPL HOLDINGS, INC"), which searches badly and
collides with the "Name, City" watchlist format, so each is cleaned to
"LPL Holdings" and written as "Name | City".

The output files are gitignored: they are the portfolio, and this repo is public.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Name cleaning lives in watchlist.py, which is also the module that reads the
# rosters back, so the two can never disagree about how a name is spelled.
from watchlist import clean_name  # noqa: E402

ROOT = Path(__file__).resolve().parent
WATCHLISTS = ROOT / "data" / "watchlists"

DEFAULT_TENANTS = (
    Path.home() / "OneDrive - UC San Diego" / "Desktop" / "AAT"
    / "AAT Retail and Office Tenant Roster 072026 aw.xlsx"
)
DEFAULT_COMPETITORS = (
    Path.home() / "OneDrive - UC San Diego" / "Desktop" / "AAT" / "Competitor List.xlsx"
)

# Sheets holding "Tenant Name" + "City", with a title row above the header.
TENANT_SHEETS = {"office": "Office", "retail": "Retail & MU"}

def _load_workbook(path: Path):
    """Open a workbook, copying it first if the original cannot be read.

    OneDrive-synced files and workbooks still open in Excel deny direct reads, so
    fall back to a throwaway copy rather than making the user close Excel.
    """
    import openpyxl

    try:
        return openpyxl.load_workbook(path, read_only=True, data_only=True)
    except PermissionError:
        import shutil
        import tempfile

        tmp = Path(tempfile.gettempdir()) / f"_ingest_{path.name}"
        shutil.copy2(path, tmp)
        print(f"  (locked by another program - read a copy at {tmp.name})")
        return openpyxl.load_workbook(tmp, read_only=True, data_only=True)


def read_sheet_pairs(path: Path, sheet: str, name_col: str, city_col: str) -> list[tuple[str, str]]:
    """(name, city) pairs from a sheet whose header row may not be row 1."""
    wb = _load_workbook(path)
    if sheet not in wb.sheetnames:
        names = wb.sheetnames
        wb.close()
        sys.exit(f"error: sheet {sheet!r} not in {path.name}. Found: {names}")
    rows = [r for r in wb[sheet].iter_rows(values_only=True)]
    wb.close()

    header = None
    hdr_i = None
    for i, row in enumerate(rows[:15]):
        vals = [str(c).strip().lower() if c else "" for c in row]
        if name_col.lower() in vals:
            hdr_i, header = i, vals
            break
    if header is None:
        sys.exit(f"error: no {name_col!r} header found in {sheet!r} of {path.name}")

    ni = header.index(name_col.lower())
    ci = header.index(city_col.lower()) if city_col.lower() in header else None

    out = []
    for row in rows[hdr_i + 1:]:
        if not row or ni >= len(row) or not row[ni]:
            continue
        name = clean_name(row[ni])
        if not name:
            continue
        city = ""
        if ci is not None and ci < len(row) and row[ci]:
            city = re.sub(r"\s+", " ", str(row[ci]).strip()).replace("|", "/")
        out.append((name, city))
    return out


def dedupe(pairs: list[tuple[str, str]]) -> list[tuple[str, str]]:
    """One row per (name, city), keeping first-seen order."""
    seen, out = set(), []
    for name, city in pairs:
        key = (name.lower(), city.lower())
        if key in seen:
            continue
        seen.add(key)
        out.append((name, city))
    return out


def write_watchlist(path: Path, pairs: list[tuple[str, str]], title: str, source: Path) -> None:
    lines = [
        f"# {title} - one entity per line. Drives LIVE runs (serve.py).",
        f"# Generated by ingest.py from {source.name}. Re-run ingest.py to refresh.",
        "#",
        "# Format:  Name | City     (pipe is unambiguous; 'Name, City' also parses)",
        "#",
        "# PRIVATE: this file is gitignored. It is the portfolio list, and the repo",
        "# is public. Only names and cities are here - no rent, GLA, or lease terms.",
        "",
    ]
    lines += [f"{name} | {city}" if city else name for name, city in pairs]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def describe(paths: list[Path]) -> None:
    for path in paths:
        print("=" * 74)
        print(path)
        if not path.exists():
            print("  MISSING")
            continue
        wb = _load_workbook(path)
        for ws in wb.worksheets:
            first = next(ws.iter_rows(values_only=True), ())
            cells = [str(c)[:20] if c else "" for c in (first or ())[:8]]
            print(f"  '{ws.title}' rows={ws.max_row} cols={ws.max_column}")
            print(f"     row0: {cells}")
        wb.close()


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--tenants", default=str(DEFAULT_TENANTS))
    ap.add_argument("--competitors", default=str(DEFAULT_COMPETITORS))
    ap.add_argument("--segment", default="all", choices=["all", "office", "retail"])
    ap.add_argument("--city", default="", help="keep only this city (case-insensitive)")
    ap.add_argument("--limit", type=int, default=0, help="cap entities per list")
    ap.add_argument("--only", default="both", choices=["both", "tenants", "competitors"])
    ap.add_argument("--list", action="store_true", help="describe the workbooks and exit")
    args = ap.parse_args()

    tpath, cpath = Path(args.tenants), Path(args.competitors)

    if args.list:
        describe([tpath, cpath])
        return 0

    WATCHLISTS.mkdir(parents=True, exist_ok=True)
    written = []

    if args.only in ("both", "tenants"):
        if not tpath.exists():
            sys.exit(f"error: tenant workbook not found: {tpath}")
        wanted = list(TENANT_SHEETS) if args.segment == "all" else [args.segment]
        pairs: list[tuple[str, str]] = []
        for key in wanted:
            got = read_sheet_pairs(tpath, TENANT_SHEETS[key], "Tenant Name", "City")
            print(f"  {TENANT_SHEETS[key]}: {len(got)} rows")
            pairs += got
        if args.city:
            pairs = [p for p in pairs if p[1].lower() == args.city.lower()]
        pairs = dedupe(pairs)
        if args.limit:
            pairs = pairs[: args.limit]
        write_watchlist(WATCHLISTS / "tenants.txt", pairs, "Tenant watchlist", tpath)
        written.append(("tenants", len(pairs)))

    if args.only in ("both", "competitors"):
        if not cpath.exists():
            sys.exit(f"error: competitor workbook not found: {cpath}")
        # The name column is headed "Where" in this workbook, not "Competitor".
        pairs = read_sheet_pairs(cpath, "Competitor List ", "Where", "City")
        if args.city:
            pairs = [p for p in pairs if p[1].lower() == args.city.lower()]
        pairs = dedupe(pairs)
        if args.limit:
            pairs = pairs[: args.limit]
        write_watchlist(WATCHLISTS / "competitors.txt", pairs, "Competitor watchlist", cpath)
        written.append(("competitors", len(pairs)))

    print()
    total = 0
    for name, count in written:
        print(f"{name}: {count} entities -> data/watchlists/{name}.txt")
        total += count
    print(f"\n{total} entities total.")
    print(f"Live-run cost at 2 queries each: ~{total * 2} Tavily credits, {total} LLM calls.")
    if total > 60:
        print("That is a lot for one click - use Cap entities in the runner, or")
        print("re-run with --segment / --city / --limit for a demo-sized list.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
